# Generated by Django 5.1.4 on 2025-02-16 15:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFoodIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('meal_type', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('carbs', models.FloatField()),
                ('fat', models.FloatField()),
                ('protein', models.FloatField()),
                ('calories', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodItemsdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('energy', models.IntegerField()),
                ('protien', models.DecimalField(decimal_places=5, max_digits=10)),
                ('carbohydrate', models.DecimalField(decimal_places=5, max_digits=10)),
                ('fat', models.DecimalField(decimal_places=5, max_digits=10)),
                ('GmWt_1', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('GmWt_Desc1', models.CharField(max_length=100, null=True)),
                ('GmWt_2', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('GmWt_Desc2', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'FoodItemsFinal',
            },
        ),
    ]
